import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../css/main.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { createIconsTypes } from '@/utils/createIcons';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  createIconsTypes();
  return (
    <html lang="en">
      <head>
        <meta property="og:url" content="https://wallet-stellar.vercel.app/" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="Tap4Change donor" />
        <meta
          property="og:description"
          content="Aplicacion para donar a caridades de todo el mundo con una amplia seleccion."
        />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/damjxqb5f/image/upload/v1704225504/avatar_7_ftmrh8.png"
        />
      </head>
      <body className={`${inter.className} body`}>
        <Header />
        <div className="body__children">
          <ToastContainer />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
