import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../css/main.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { createIconsTypes } from '@/utils/createIcons';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  createIconsTypes();
  return (
    <html lang="en">
      <body className={`${inter.className} body`}>
        <Header />
        <div className="body__children">
          <ToastContainer />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
